
name: GitHub CI Test

# https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-python

on: push

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      
      - name: Lint with flake8
        run: flake8 .
        continue-on-error: false
      
      - name: Test with unittest
        run: coverage run --source tests/ -m unittest discover && coverage report

      # Runs a single command using the runners shell
      - name: Run a Python script
        run: python src/main.py
